name: 'Setup Brioche'
description: 'GitHub Action to install Brioche on the runner'
author: 'brioche-dev'
inputs:
  version:
    description: 'Version of Brioche to install'
    required: false
    default: 'v0.1.3'
  install-dir:
    description: 'Directory where Brioche should be installed'
    required: false
    default: '$HOME/.local/bin'
runs:
  using: 'composite'
  steps:
    - name: Install Brioche
      shell: bash
      run: |
        "$GITHUB_ACTION_PATH"/install-brioche.sh
      env:
        install_dir: ${{ inputs.install-dir }}
        version: ${{ inputs.version }}
