name: 'Setup Brioche'
description: 'GitHub Action to install Brioche on the runner'
author: 'brioche-dev'
inputs:
  version:
    description: 'Version of Brioche to install'
    required: false
    default: 'v0.1.3'
  install-dir:
    description: 'Directory where Brioche should be installed'
    required: false
    default: '$HOME/.local/bin'
runs:
  using: 'composite'
  steps:
    - name: Install Brioche
      shell: bash
      run: |
        chmod +x $GITHUB_ACTION_PATH/install-brioche.sh
        $GITHUB_ACTION_PATH/install-brioche.sh "${{ inputs.install-dir }}" ${{ inputs.version }}
      
    - name: Add Brioche to PATH
      shell: bash
      run: echo "${{ inputs.install-dir }}" >> $GITHUB_PATH
