name: "Setup Brioche"
description: "GitHub Action to install Brioche on the runner"
author: "brioche-dev"
branding:
  color: "orange"
  icon: "box"
inputs:
  version:
    description: "Version of Brioche to install"
    required: false
    default: "v0.1.5"
  install-dir:
    description: "Directory where Brioche should be installed"
    required: false
    default: "$HOME/.local/bin"
  install-apparmor:
    description: "Install AppArmor profile for Brioche. Defaults to 'auto'"
    required: false
    default: "auto"
runs:
  using: "composite"
  steps:
    - name: Install Brioche
      shell: bash
      run: |
        "$GITHUB_ACTION_PATH"/install-brioche.sh
      env:
        install_dir: ${{ inputs.install-dir }}
        version: ${{ inputs.version }}
        install_apparmor: ${{ inputs.install-apparmor }}
