name: Publish GitHub Actions

on:
  push:
    tags:
      - v?[0-9]+.[0-9]+.[0-9]+-?**

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Determine versions
        id: versions
        run: |
          major_version="$(cat VERSION | cut -f1 -d.)"
          echo "major-version=$major_version" | tee -a "$GITHUB_OUTPUT"
      - name: Update versions
        run: |
          echo "Pushing tag $major_version"
          git tag -f "$major_version"
          git push -f origin "$major_version"
        env:
          major_version: ${{ steps.versions.outputs.major-version }}
