name: Publish GitHub Actions

on:
  push:
    tags:
      - v?[0-9]+.[0-9]+.[0-9]+-?**

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Determine versions
        id: versions
        run: |
          full_version="$(cat VERSION)"
          major_version="$(echo "$full_version" | cut -f1 -d.)"
          echo "full-version=$full_version" | tee -a "$GITHUB_OUTPUT"
          echo "major-version=$major_version" | tee -a "$GITHUB_OUTPUT"
      - name: Update versions
        run: |
          echo "Pushing tag v${major_version}"
          git tag -f "v${major_version}"
          git push -f origin "v${major_version}"
        env:
          full_version: ${{ steps.versions.outputs.full-version }}
          major_version: ${{ steps.versions.outputs.major-version }}
