name: Test Brioche Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  smoke-test-setup-brioche:
    strategy:
      matrix:
        runs-on:
          - ubuntu-22.04
          - ubuntu-24.04
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Brioche
        uses: ./ # Uses an action in the root directory

      - &verify-brioche
        name: Verify Brioche installation
        run: |
          brioche --version
          brioche install -r hello_world
          hello-world

          WATERMARK="$(date -uIs)"
          sed -i "s/\${WATERMARK}/${WATERMARK}/g" example-project/project.bri
          brioche build -p example-project -o output

  test-setup-brioche:
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            channel: stable
          - runs-on: ubuntu-latest
            channel: nightly
          - runs-on: ubuntu-latest-arm
            channel: stable
          - runs-on: ubuntu-latest-arm
            channel: nightly
    runs-on: ${{ matrix.runs-on }}
    continue-on-error: ${{ matrix.runs-on == 'ubuntu-latest-arm' && matrix.channel == 'stable' }} # Brioche stable does not support ARM architecture
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Brioche
        uses: ./ # Uses an action in the root directory
        with:
          channel: ${{ matrix.channel }}

      - *verify-brioche
