name: Test Brioche Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-brioche:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Brioche
        uses: ./ # Uses an action in the root directory
        with:
          version: 'v0.1.3'  # Optional, defaults to v0.1.3

      - name: Verify Brioche installation
        run: |
          brioche --version
          brioche install -r hello_world
          hello-world
