name: Test Brioche Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-setup-brioche:
    strategy:
      matrix:
        runs-on:
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Brioche
        uses: ./ # Uses an action in the root directory
        with:
          version: 'v0.1.3' # Optional, defaults to v0.1.3

      - name: Verify Brioche installation
        run: |
          brioche --version
          brioche install -r hello_world
          hello-world

          WATERMARK="$(date -uIs)"
          sed -i "s/\${WATERMARK}/${WATERMARK}/g" example-project/project.bri
          brioche build -p example-project -o output
