name: Test Brioche Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

verify-brioche: &verify-brioche
  name: Verify Brioche installation
  run: |
    brioche --version
    brioche install -r hello_world
    hello-world

    WATERMARK="$(date -uIs)"
    sed -i "s/\${WATERMARK}/${WATERMARK}/g" example-project/project.bri
    brioche build -p example-project -o output

jobs:
  smoke-test-setup-brioche:
    strategy:
      matrix:
        runs-on:
          - ubuntu-22.04
          - ubuntu-24.04
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Brioche
        uses: ./ # Uses an action in the root directory

      - *verify-brioche

  test-setup-brioche-channel:
    strategy:
      matrix:
        channel:
          - stable
          - nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Brioche
        uses: ./ # Uses an action in the root directory
        with:
          channel: ${{ matrix.channel }}

      - *verify-brioche

  # This test can only be run on Brioche nightly as for now
  test-setup-brioche-arm64-runner:
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest-arm
          - ubuntu-latest-arm
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Brioche
        uses: ./ # Uses an action in the root directory
        with:
          channel: nightly

      - *verify-brioche
